<?php
$id=rand(1,20);
$image[1]='https://zxj18.github.io/yun/img/1.jpg';
$image[2]='https://zxj18.github.io/yun/img/2.jpg';
$image[3]='https://zxj18.github.io/yun/img/3.jpg';
$image[4]='https://zxj18.github.io/yun/img/4.jpg';
$image[5]='https://zxj18.github.io/yun/img/5.jpg';
$image[5]='https://zxj18.github.io/yun/img/6.jpg';
$image[5]='https://zxj18.github.io/yun/img/7.jpg';
$image[5]='https://zxj18.github.io/yun/img/8.jpg';
$image[5]='https://zxj18.github.io/yun/img/9.jpg';
$image[5]='https://zxj18.github.io/yun/img/10.jpg';
$image[5]='https://zxj18.github.io/yun/img/11.jpg';
$image[5]='https://zxj18.github.io/yun/img/12.jpg';
$image[5]='https://zxj18.github.io/yun/img/13.jpg';
$image[5]='https://zxj18.github.io/yun/img/14.jpg';
$image[5]='https://zxj18.github.io/yun/img/15.jpg';
$image[5]='https://zxj18.github.io/yun/img/16.jpg';
$image[5]='https://zxj18.github.io/yun/img/17.jpg';
$image[5]='https://zxj18.github.io/yun/img/18.jpg';
$image[5]='https://zxj18.github.io/yun/img/19.jpg';
$image[5]='https://zxj18.github.io/yun/img/20.jpg';
header("location:$image[$id]");
?>
